"""Builds src/icons.json from every icon grid: the base set, the extras/portraits and the
game-specific ones below (one per skill-tree node, a flask per chemical, a splat per dirt).

    python3 tools/icons_game.py            # writes src/icons.json
    python3 tools/icons_game.py --sheet    # also writes a contact sheet next to this script

Grids are 16 letters wide, one letter per pixel; '.' is transparent. Letters map to PAL."""
import json, os, sys
sys.path.insert(0, os.path.dirname(__file__))
import icons_base as base
import icons_extra as extra

PAL = base.PAL
# dirt shades (thin film, mid, deep crust) straight from GRIME_TYPES in src/core.js
PAL.update({
    'a':'#b09a6b','d':'#8b7449',                 # dust
    'u':'#9c7a52','z':'#70522f',                 # mud
    '1':'#93b166','2':'#61883b','3':'#3d6425',   # moss
    'e':'#7f776a','f':'#524c43','o':'#2d2a24',   # grease
    '4':'#8c8c93','5':'#5d5d65','6':'#34343b',   # soot
    'x':'#c0cdc5','y':'#93a79d','q':'#657a70',   # salt
    '7':'#c98a5a','8':'#9a5a2e','9':'#6a3a18',   # rust
    'i':'#d43d6a','j':'#2f7fd8','k':'#f2c12e',   # graffiti
    'A':'#e6e6e6','I':'#9a9a9a',                 # steel
})

GAME = {
# ---- skill tree: Water limb -------------------------------------------------
'nozzle': """
................
..KKKK..........
..KGGGK.........
..KGAGGK........
..KGAGGGKKKK....
..KGAGGGGGGGK...
..KGGGGGGGGGGK..
..KGGGGGGGGGGK..
..KGGgGGGGGGGK..
..KGggGgggggK...
..KGggGgggK.....
..KGggGK..W.hW..
..KKKK...WhW.W..
........W.W.hW..
.......h.W..W...
................
""",
'cone': """
................
.......KK.......
......KGGK......
......KGgK......
......KGgK......
.....KWWWWK.....
....KWhWWWwK....
....KWhWWWwK....
...KWWhWWWwwK...
...KWWhWWWwwK...
..KWWWhWWWwwwK..
..KWWWhWWWwwwK..
.KWWWWhWWWwwwwK.
.KWWWWhWWWwwwwK.
..KKKKKKKKKKKK..
................
""",
'pump': """
................
.....KKKKKK.....
....KAAAAAAK....
...KAAKKKKAAK...
...KAKHHHHKAK...
...KAKHKHHKAK...
...KAKHHKHKAK...
...KAAKKKKAAK...
..KKAAAAAAAAKK..
.KCCCCCCCCCCCCK.
.KCCcCCCCCCCcCK.
.KCcccCCCCCcccK.
.KCCCCCCCCCCCCK.
.KKKKKKKKKKKKKK.
..KGGK....KGGK..
..KKKK....KKKK..
""",
'lance': """
...............K
..............KH
.............KHS
............KSSK
...........KSSK.
..........KSSK..
.........KGGK...
........KGGK....
.......KGGK.....
......KGGK......
.....KGGK.......
...KKGGK........
..KggGK.........
.KggKK..........
.KgK............
.KK.............
""",
# ---- Tank limb ---------------------------------------------------------------
'faucet': """
................
......KKKK......
.....KAAAAK.....
......KKKK......
.......KK.......
..KKKKKAAKKKK...
.KAAAAAAAAAAAK..
.KAAAAAAAAAAAAK.
.KIIIIIIIIIIIAK.
..KKKKKKKKKKKAK.
............KAK.
............KK..
...........KWK..
...........KhK..
............W...
............W...
""",
'valve': """
................
.......KK.......
......KCCK......
.....KCCCCK.....
......KCCK......
..KKKKKCCKKKKK..
.KCCCCCCCCCCCCK.
..KKKKKCCKKKKK..
......KCCK......
....KKKAAKKK....
...KAAAAAAAAK...
..KAIIAAAAIIAK..
..KAAAAAAAAAAK..
..KAAAAAAAAAAK..
...KKKKKKKKKK...
................
""",
# ---- Business limb ------------------------------------------------------------
'scroll': """
................
....KKKKKKKK....
...KPFFFFFFPK...
...KPFKKKKFPK...
...KPFFFFFFPK...
...KPFKKKFFPK...
...KPFFFFFFPK...
...KPFKKKKFPK...
...KPFFFFFFPK...
...KPFKKFFFPK...
...KPFFFFCFPK...
...KPFFFCCCPK...
...KPFFFFFFPK...
....KKKKKKKK....
...KppppppppK...
....KKKKKKKK....
""",
'briefcase': """
................
.....KKKKKK.....
.....KBBBBK.....
.....K....K.....
.KKKKKKKKKKKKKK.
.KBBBBBBBBBBBBK.
.KBBBBBBBBBBBBK.
.KBBBBBKKBBBBBK.
.KKKKKKSSKKKKKK.
.KbbbbbKKbbbbbK.
.KbbbbbbbbbbbbK.
.KbbbbbbbbbbbbK.
.KbbbbbbbbbbbbK.
.KbbbbbbbbbbbbK.
.KKKKKKKKKKKKKK.
................
""",
# ---- Crew limb --------------------------------------------------------------
'heart': """
................
..KKKK....KKKK..
.KCCCCK..KCCCCK.
KCHHCCCKKCCCCCcK
KCHCCCCCCCCCCCcK
KCCCCCCCCCCCCccK
KCCCCCCCCCCCcccK
.KCCCCCCCCCcccK.
..KCCCCCCCcccK..
...KCCCCCcccK...
....KCCCcccK....
.....KCcccK.....
......KccK......
.......KK.......
................
................
""",
'watergun': """
.....KKKKK......
....KhhhhhK.....
...KhhWWWWWK....
...KhWWWWWWK....
...KKKWWWWKK....
.KKKKKKKKKKKKKK.
KLLQQLLLLLLLLLSK
KLLLLLLLLLLLLLSK
KLLLLLLLLKLLKKKK
.KKKLLLKKKKCCCK.
...KSSK...KCCK..
...KSSK...KKK...
...KSsK.........
...KssK.........
...KKKK.........
................
""",
'calendar': """
................
....K......K....
...KGK....KGK...
.KKKKKKKKKKKKKK.
.KCCCCCCCCCCCCK.
.KCCCCCCCCCCCCK.
.KKKKKKKKKKKKKK.
.KFFKKFFKKFFKKFK
.KFFFFFFFFFFFFFK
.KFKKFFKKFFKKFFK
.KFFFFFFFFFFFFFK
.KFKKFFKKFFSSFFK
.KFFFFFFFFFSSFFK
.KKKKKKKKKKKKKKK
................
................
""",
'family': """
................
....KK....KK....
...KNNK..KNNK...
...KNNK..KNNK...
....KK....KK....
...KWWK..KCCK...
..KWWWWKKCCCCK..
..KWWWWKKCCCCK..
..KWWWWKKCCCCK..
...KWWK..KCCK...
...KwwK..KccK...
...KwwK..KccK...
...KwwK..KccK...
...KKKK..KKKK...
................
................
""",
# ---- chemicals: the flask's liquid is the mid shade of the dirt it cuts -----
'flaskMoss': """
................
......KKKK......
......KOOK......
......KOOK......
......KOOK......
......KOOK......
.....KOOOOK.....
....KOOOOOOK....
...KOOOOOOOOK...
..KOOO222OOOOK..
..KO22222222OK..
..K22222322222K.
..K22322222322K.
..K22222222223K.
...KKKKKKKKKK...
................
""",
'flaskGrease': """
................
......KKKK......
......KOOK......
......KOOK......
......KOOK......
......KOOK......
.....KOOOOK.....
....KOOOOOOK....
...KOOOOOOOOK...
..KOOOfffOOOOK..
..KOffffffffOK..
..KfffffofffffK.
..KffofffffoffK.
..KffffffffffoK.
...KKKKKKKKKK...
................
""",
'flaskRust': """
................
......KKKK......
......KOOK......
......KOOK......
......KOOK......
......KOOK......
.....KOOOOK.....
....KOOOOOOK....
...KOOOOOOOOK...
..KOOO888OOOOK..
..KO88888888OK..
..K88888988888K.
..K88988888988K.
..K88888888889K.
...KKKKKKKKKK...
................
""",
'flaskPaint': """
................
......KKKK......
......KOOK......
......KOOK......
......KOOK......
......KOOK......
.....KOOOOK.....
....KOOOOOOK....
...KOOOOOOOOK...
..KOOOiiiOOOOK..
..KOiiiiiiiiOK..
..KiiiiiRiiiiiK.
..KiiRiiiiiRiiK.
..KiiiiiiiiiiRK.
...KKKKKKKKKK...
................
""",
}

def splat(light, mid, dark):
    """A blob of dirt in three shades; each dirt type gets one in its own colours."""
    g = """
................
.....KK...K.....
....KmmK.KmK....
...KmmmmKmmmK...
..KmmllmmmmmmK..
..KmlllmmmmddK..
.KmmllmmmmmdddK.
.KmmmmmmmmmddK..
.KmmmmmmmmdddK..
..KmmmmmmmdddK..
..KKmmmmmddddK..
..KmKmmmdddKK...
.KmK.KmddddK....
.KK...KKdKK.....
.......KK.......
................
"""
    return g.replace('l', light).replace('m', mid).replace('d', dark)

GAME.update({
    'dirtDust':     splat('P', 'a', 'd'),
    'dirtMud':      splat('a', 'u', 'z'),
    'dirtMoss':     splat('1', '2', '3'),
    'dirtGrease':   splat('e', 'f', 'o'),
    'dirtSoot':     splat('4', '5', '6'),
    'dirtSalt':     splat('x', 'y', 'q'),
    'dirtRust':     splat('7', '8', '9'),
    'dirtGraffiti': splat('k', 'i', 'j'),
})

def build():
    out = {}
    for n, g in base.ICONS.items(): out[n] = base.svg(g, 16)
    for n, g in extra.EXTRA.items(): out[n] = base.svg(g, 16)
    for n, g in GAME.items(): out[n] = base.svg(g, 16)
    for n, g in base.LOGOS.items(): out[n] = base.svg(g, 24)
    for n, g in extra.PORTRAITS.items(): out['p_' + n] = base.svg(g, 24)
    # strip fixed width/height so CSS sizes them
    for k, v in out.items(): out[k] = v.replace(' width="16" height="16"', '').replace(' width="24" height="24"', '')
    return out

if __name__ == '__main__':
    out = build()
    dest = os.path.join(os.path.dirname(__file__), '..', 'src', 'icons.json')
    json.dump(out, open(dest, 'w'))
    print(len(out), 'icons ->', os.path.relpath(dest))
    if '--sheet' in sys.argv:
        sheet = '<html><body style="background:#8fcbe4;padding:20px;display:flex;flex-wrap:wrap;gap:16px">'
        for n in out:
            big = out[n].replace('<svg ', '<svg style="width:64px;height:64px;image-rendering:pixelated" ')
            sheet += '<div style="text-align:center;font:12px monospace"><div style="width:64px;height:64px">' + big + '</div>' + n + '</div>'
        path = os.path.join(os.path.dirname(__file__), 'icon-sheet.html')
        open(path, 'w').write(sheet + '</body></html>')
        print('sheet ->', os.path.relpath(path))
