import os
PAL = {
 'K':'#3a2010','S':'#f6c744','s':'#c8901a','H':'#ffe08a','C':'#e8744c','c':'#a03a1c',
 'W':'#58a6d8','w':'#26668f','h':'#a5dcf3','L':'#74b247','l':'#386a1b','P':'#f8dc9c',
 'p':'#e9c274','B':'#b46a2c','b':'#7e451a','G':'#b9b4a6','g':'#6f6a60','E':'#f39a52',
 'R':'#d980a4','r':'#8a2d52','F':'#fff0c4',
}
ICONS = {
'coin': """
.....KKKKKK.....
...KKSSSSSSKK...
..KSHHSSSSSSSK..
.KSHSSSSKSSSSsK.
.KSHSSSKKKSSSsK.
KSHSSSKSSSKSSssK
KSSSSSKSSSSSSssK
KSSSSSSKKKSSSssK
KSSSSSSSSSKSSssK
KSSSSSKSSSKSSssK
KSSSSSSKKKSSsssK
.KSSSSSSKSSsssK.
.KSSSSSSSSssssK.
..KSSSSssssssK..
...KKssssssKK...
.....KKKKKK.....
""",
'star': """
.......KK.......
......KSSK......
......KSSK......
.....KSHSSK.....
.....KSHSSK.....
KKKKKKSHSSKKKKKK
KSSSSSSSSSSSSSsK
.KSSSSSSSSSSSsK.
..KSSSSSSSSSsK..
...KSSSSSSSsK...
...KSSSSSSSsK...
..KSSSSSSSSssK..
..KSSSKKKKSsssK.
.KSSKK....KKssK.
.KKK........KKK.
................
""",
'flame': """
.......K........
......KCK.......
......KCK.......
.....KCCCK......
.....KCCCK..K...
....KCCCCCKKCK..
....KCCSCCCKCK..
...KCCSSSCCCCCK.
...KCCSHSSCCCCK.
..KCCSSHHSSCCCCK
..KCCSSHHSSCCCcK
..KCCSSHHSSCCccK
..KCCCSSSSCCcccK
...KCCCSSCCcccK.
....KCCCCCcccK..
.....KKKKKKKK...
""",
'hardhat': """
................
................
......KKKK......
....KKSSSSKK....
...KSSHHSSSSK...
..KSSHSSSSSSsK..
..KSSHSSSSSSsK..
..KSSSSSSSSSsK..
..KSSSSSSSSSsK..
.KKSSSSSSSSSsKK.
KSSSSSSSSSSSsssK
KssssssssssssssK
.KKKKKKKKKKKKKK.
................
................
................
""",
'drop': """
.......K........
......KWK.......
......KWK.......
.....KWWWK......
.....KWWWK......
....KWhWWWK.....
....KWhWWWK.....
...KWhhWWWWK....
...KWhWWWWWwK...
..KWhhWWWWWwK...
..KWhWWWWWWwwK..
..KWWWWWWWWwwK..
..KWWWWWWWwwwK..
...KWWWWWwwwK...
....KWWwwwwK....
.....KKKKKK.....
""",
'sparkle': """
.......KK.......
.......KK.......
......KHHK......
......KHHK......
......KHHK......
.....KSHHSK.....
....KSSHHSSK....
KKKKKSSHHSSKKKKK
KHHSSSSHHSSSSHHK
KKKKKSSHHSSKKKKK
....KSSHHSSK....
.....KSHHSK.....
......KHHK......
......KHHK......
......KHHK......
.......KK.......
""",
'wrench': """
.........KKKK...
........KGGGGK..
.......KGGKKGGK.
.......KGGK.KGK.
.......KGGKKKgK.
......KKGGGGGgK.
.....KGGGKGGgK..
....KGGGK.KKK...
...KGGGK........
..KGGGK.........
.KGGGgK.........
KGGGgK..........
KGGgK...........
KGgK............
KKK.............
................
""",
'map': """
................
................
KKKKKKKKKKKKKKKK
KPPPPKLLLLKPPPPK
KPPLPKLLLLKPPPPK
KPPPPKLLLLKPPWPK
KPPPPKLLLLKPWWPK
KPPPPKLLcLKPPWPK
KPPPPKLLLLKPPPPK
KPPPPKLLLLKPPPPK
KPPPPKLLLLKPPPPK
KPpppKlLLLKppppK
KKKKKKKKKKKKKKKK
................
................
................
""",
'clock': """
.....KKKKKK.....
...KKPPPPPPKK...
..KPPPPKKPPPPK..
.KPPPPPKKPPPPPK.
.KPPPPPKKPPPPPK.
KPPPPPPKKPPPPPPK
KPPPPPPKKPPPPPPK
KPPPPPPKKKKKPPPK
KPPPPPPPPPPKPPPK
KPPPPPPPPPPPPPPK
KPPPPPPPPPPPPppK
.KPPPPPPPPPPppK.
.KPPPPPPPPPpppK.
..KPPPPPPppppK..
...KKppppppKK...
.....KKKKKK.....
""",
'lock': """
................
.....KKKKKK.....
....KGGGGGGK....
...KGGKKKKGGK...
...KGK....KGK...
...KGK....KGK...
...KGK....KGK...
.KKKKKKKKKKKKKK.
KSSSSSSSSSSSSssK
KSSSSSSKKSSSSssK
KSSSSSSKKSSSSssK
KSSSSSSSKSSSSssK
KSSSSSSSSSSSsssK
KSsssssssssssssK
.KKKKKKKKKKKKKK.
................
""",
'check': """
................
................
.............KK.
............KLLK
...........KLLLK
..........KLLLK.
.KK......KLLLK..
KLLK....KLLLK...
KLLLK..KLLLK....
.KLLLKKLLLK.....
..KLLLLLLK......
...KLLLLK.......
....KLLK........
.....KK.........
................
................
""",
'arrow-right': """
................
................
....KK..........
....KSK.........
....KSSK........
....KSSSK.......
....KSSSSK......
....KSSSSSK.....
....KSSSSSK.....
....KSSSSK......
....KSSSK.......
....KSSK........
....KSK.........
....KK..........
................
................
""",
'bill': """
..KKKKKKKKKKKK..
..KFFFFFFFFFFK..
..KFFFFFFFFFFK..
..KFKKKKKKKFFK..
..KFFFFFFFFFFK..
..KFKKKKKKFFFK..
..KFFFFFFFFFFK..
..KFKKKKKKKKFK..
..KFFFFFFFFFFK..
..KFFFFFFcccFK..
..KFFFFFFcccFK..
..KFFFFFFFFFFK..
..KFKFFKFFKFFK..
..KKFKKFKKFKKK..
................
................
""",
'trophy': """
................
.KKKKKKKKKKKKKK.
KSKSSSSSSSSSSKSK
KSKSHHSSSSSSSKSK
KSKSHSSSSSSSsKSK
KSKSHSSSSSSSsKSK
KKKSSSSSSSSSsKKK
...KSSSSSSSssK..
....KSSSSSssK...
.....KSSSssK....
......KSssK.....
.......KsK......
......KbbbK.....
.....KBBBBbK....
....KBBBBBBbK...
....KKKKKKKKK...
""",
'wand': """
...............h
............h...
..............h.
...........h....
..KKKKKKKKKKKK..
.KWWWWWWWWWWWWKh
KWwWWWWWWWWWWWK.
KWKKKKKKWWKKKKK.
KKK.....KWWK....
........KwwK....
........KwwK....
.......KKwwK....
.......KwwwK....
.......KKKKK....
................
................
""",
'book': """
................
..KKKKKKKKKKKK..
.KBBBBBBKPPPPPK.
.KBBBBBBKPKKKPK.
.KBBBBBBKPPPPPK.
.KBBBBBBKPKKKPK.
.KBBBBBBKPPPPPK.
.KBBBBBBKPKKKPK.
.KBBBBBBKPPPPPK.
.KBBBBBBKPPPPPK.
.KbBBBBBKPPPPPK.
.KbbbbbbKpppppK.
.KKKKKKKKKKKKKK.
................
................
................
""",
'chart': """
................
..............K.
..........KKKKK.
..........KLLLK.
......KKKKKLLLK.
......KWWWKLLLK.
..KKKKKWWWKLLLK.
..KSSSKWWWKLLLK.
..KSSSKWWWKLLLK.
..KSSSKWWWKLLLK.
..KSSSKWWWKLLLK.
..KsssKwwwKlllK.
KKKKKKKKKKKKKKKK
................
................
................
""",
'truck': """
................
................
................
..KKKKKKK.......
.KPPPPPPPK.KKKK.
KPPWWWPPPPKWWWWK
KPPWWWPPPPKWhhWK
KPPPPPPPPPKWWWWK
KppppppppPKWWwwK
KKKKKKKKKKKKKKKK
KbbbbbbbbbbbbbbK
KKKKKKKKKKKKKKKK
..KKK.....KKK...
.KKgKK...KKgKK..
.KKgKK...KKgKK..
..KKK.....KKK...
""",
}
LOGOS = {
'mascot': """
...........K............
..........KWK...........
..........KWK...........
.........KWWWK..........
.........KWWWK..........
........KWhWWWK.........
........KWhWWWK.........
.......KWhhWWWWK........
......KWhhWWWWWWK.......
.....KWhhWWWWWWWwK......
....KCCCCCCCCCCCCCK.....
...KWhWWWWWWWWWWWwwK....
..KWhhWWWWWWWWWWWwwwK...
..KWhWWKKWWWWKKWWwwwK...
.KWhWWWKKWWWWKKWWWwwwK..
.KWWWWWWWWWWWWWWWWwwwK..
.KWWWEEWWWWWWWWEEWwwwK..
.KWWWWWWKWWWWWWKWWwwwK..
.KWWWWWWWKKKKKKWWWwwwK..
..KWWWWWWWWWWWWWWwwwwK..
..KWWWWWWWWWWWWwwwwwK...
...KWWWWWWWWWwwwwwwK....
....KKWWWWwwwwwwKK......
......KKKKKKKKKK........
""",
}
def svg(grid, size):
    rows=[r for r in grid.strip('\n').split('\n')]
    assert len(rows)==size, (len(rows), rows[0])
    out=[]
    for y,row in enumerate(rows):
        assert len(row)==size, (y,len(row),row)
        x=0
        while x<size:
            ch=row[x]
            if ch=='.': x+=1; continue
            x0=x
            while x<size and row[x]==ch: x+=1
            out.append(f'<rect x="{x0}" y="{y}" width="{x-x0}" height="1" fill="{PAL[ch]}"/>')
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {size} {size}" width="{size}" height="{size}" shape-rendering="crispEdges">'
            + ''.join(out) + '</svg>')
if __name__ == '__main__':
    for name,g in ICONS.items():
        open(f'ds/project/assets/Icons/{name}.svg','w').write(svg(g,16))
    for name,g in LOGOS.items():
        open(f'ds/project/assets/Logos/{name}.svg','w').write(svg(g,24))
    print("ok", len(ICONS), "icons")
    # a contact sheet for checking
    sheet='<html><body style="background:#8fcbe4;padding:20px;display:flex;flex-wrap:wrap;gap:16px">'
    for name in list(ICONS)+list(LOGOS):
        folder='Icons' if name in ICONS else 'Logos'
        sheet+=f'<div style="text-align:center;font:12px monospace"><img src="ds/project/assets/{folder}/{name}.svg" style="width:96px;height:96px;image-rendering:pixelated"><br>{name}</div>'
    open('sheet.html','w').write(sheet+'</body></html>')
